FROM golang:1.24-alpine AS builder

WORKDIR /app

# Download modules
COPY go.mod go.sum ./
RUN go mod download

# Copy source and build
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags="-s -w" -o /app/main ./cmd/api

FROM alpine:latest AS runtime
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/main .

ENTRYPOINT ["./main"]
